### ISSUE TITLE
CayenneLPP owner has changed

### ISSUE THREAD

**Issue by Haberle83** [beegee-tokyo/WisBlock-API-V2#2]
The owner of CayenneLPP has changed from sabas1080 to electroniccats. This change broke the ability to compile my WisBlock project. I have manually fixed if by changing the library.json:

{
	"owner": "sabas1080",
	"name": "CayenneLPP",
	"version": "*"
}
 to 
{
	"owner": "electroniccats",
	"name": "CayenneLPP",
	"version": "*"
}

Here is the link describing the issue: [PlatformIO link](https://community.platformio.org/t/files-indexed-correctly-but-the-platformio-page-shows-something-else/41218/2)

**Comment by beegee-tokyo** [comment]
Fixed with V2.0.18
